### ISSUE TITLE
Improve rust-bitcoin RPC client

### ISSUE THREAD

**Issue by D4nte** [coblox/bitcoinrpc-rust-client#47]
As per #44, contribute to rust-bitcoin/rust-bitcoincore-rpc:
- Add retry on -32 rust-bitcoin/rust-bitcoincore-rpc#8
- Add test-containers

DoD:
- [ ] Pull request for changes are integrated
- [ ] README update to deprecate this repo in favor of rust-bitcoin's

**Comment by D4nte** [comment]
Looks like it's ready to go for us: https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/16/files

**Comment by thomaseizinger** [comment]
Cool!

**Comment by bonomat** [comment]
Closed because contributing back our test suite is only relevant as soon as we have deprecated this client and removed all usages from comit-rs and other users.
